{
 "title": "Embedded MPP Dashboard",
 "tags": [
  "presto",
  "jmx"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Embedded MPP Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "com_facebook_presto_dispatcher_DispatchManager_RunningQueries{job=\"presto-coordinator-jmx\"}"
    }
   ]
  },
  {
   "title": "Completed Queries (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "com_facebook_presto_dispatcher_DispatchManager_CompletedQueries_OneMinute_Count{job=\"presto-coordinator-jmx\"}"
    }
   ]
  },
  {
   "title": "Failed queries (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "com_facebook_presto_dispatcher_DispatchManager_FailedQueries_OneMinute_Count{job=\"presto-coordinator-jmx\"}"
    }
   ]
  },
  {
   "title": "Failed requests (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(instance) (com_facebook_airlift_http_client_HttpClient_RequestFailed_OneMinute_Count{job=\"presto-coordinator-jmx\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries Killed due to Out of Memory ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "com_facebook_presto_memory_ClusterMemoryManager_QueriesKilledDueToOutOfMemory{job=\"presto-coordinator-jmx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workers Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "count(up{job=\"presto-worker-jmx\"} == 1)"
    }
   ]
  },
  {
   "title": "Queued Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "com_facebook_presto_dispatcher_DispatchManager_QueuedQueries{job=\"presto-coordinator-jmx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Coordinator Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Coordinator CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_CpuLoad{job=\"presto-coordinator-jmx\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Coordinator Heap Available Memory (Gib)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "(java_lang_Memory_HeapMemoryUsage_max{job=\"presto-coordinator-jmx\"}  - java_lang_Memory_HeapMemoryUsage_used{job=\"presto-coordinator-jmx\"}) / 1024 / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Coordinator Heap Memory Usage (Gib)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{job=\"presto-coordinator-jmx\"} / 1024 /1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Coordinator Non Heap Available Memory (Gib)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{job=\"presto-coordinator-jmx\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Workers Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Workers CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_CpuLoad{job=\"presto-worker-jmx\"} * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Workers Heap Available Memory (Gib)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "(java_lang_Memory_HeapMemoryUsage_max{job=\"presto-worker-jmx\"} - java_lang_Memory_HeapMemoryUsage_used{job=\"presto-worker-jmx\"}) / 1024 / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Workers Heap Memory Usage (Gib)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{job=\"presto-worker-jmx\"} / 1024 /1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Workers Non Heap Available Memory (Gib)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{job=\"presto-worker-jmx\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}